// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq6w-i0XFYwlf6hvDe558WmjrdApctLOQ',
    appId: '1:955687176754:web:c94289c34508323cea0a2b',
    messagingSenderId: '955687176754',
    projectId: 'beehive-20153',
    authDomain: 'beehive-20153.firebaseapp.com',
    storageBucket: 'beehive-20153.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnkrX27PDp3Tu9acLSBZ7jdGSjHcLQhc8',
    appId: '1:955687176754:android:05cd903c0944c032ea0a2b',
    messagingSenderId: '955687176754',
    projectId: 'beehive-20153',
    storageBucket: 'beehive-20153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1vgrCbqJnyJIlCV3fZmxuQWWy6yppJrA',
    appId: '1:955687176754:ios:ba7288d8f907c44dea0a2b',
    messagingSenderId: '955687176754',
    projectId: 'beehive-20153',
    storageBucket: 'beehive-20153.firebasestorage.app',
    iosClientId: '955687176754-4havp3tda1f0fo6o24kusnr643tpjr5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.beehive',
  );
}
