// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTNe-M7FV91NDVEZ-gFOiFHw6cJ8wpZ1s',
    appId: '1:974951431124:web:0cd4b3f4c254cfc976f441',
    messagingSenderId: '974951431124',
    projectId: 'beehiveapp-24adf',
    authDomain: 'beehiveapp-24adf.firebaseapp.com',
    storageBucket: 'beehiveapp-24adf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB-8B9EbmeVW_TAUgkVUMAx7I78hvNuXw',
    appId: '1:974951431124:android:d824d09deecb93e776f441',
    messagingSenderId: '974951431124',
    projectId: 'beehiveapp-24adf',
    storageBucket: 'beehiveapp-24adf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCakm87QBIzDS_c0TT3m_sPnAk0rz4LqYg',
    appId: '1:974951431124:ios:8da33dcf5732095b76f441',
    messagingSenderId: '974951431124',
    projectId: 'beehiveapp-24adf',
    storageBucket: 'beehiveapp-24adf.firebasestorage.app',
    iosBundleId: 'com.example.beehive',
  );
}
