class AppRoutes {
  static const String INITIAL = "/";
  static const String WELCOME = "/welcome";
  static const String SIGN_IN = "/sign_in";
    static const String SIGN_UP= "/sign_up";
  static const String APPLICATION = "/application";
  static const String HOME = "/home";
  static const String COURSE_DETAIL = '/course_detail';
  static const String LESSON_DETAIL = '/lesson_detail';
  static const String BUY_COURSE = '/buy_course';
  static const String Profile = '/profile';
  static const String EditProfile = '/edit_profile';
  static const String Setting = '/setting';
  static const String Search = '/search';
  static const String Message = '/message';
  static const String Chat = '/chat';
  static const String VoiceCall = '/voicecall';
  static const String VideoCall = '/videocall';
  static const String Photoview = '/photoview';
  static const String Add = '/add';
  static const String Otp = '/otp';
  static const String AUTH = '/auth';
  static const Unotification = '/unotification';
  static const String FORGOT_PASSWORD = '/forgot_password';
  static const String RESET_PASSWORD = '/reset_password';
  static const String POST_DETAIL = '/post_detail';
  static const String FAVORITES = '/favorites';
  static const String CONTACT = '/contact';
}
