name: CI
on:
  push:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x" # Version stable de Java
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      # - run: flutter analyze
      # - run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x" # Version stable de Java
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - name: Set platform version in Podfile
        run: |
          cd ios
          echo "platform :ios, '15.5'" >> Podfile
      - name: Update CocoaPods repo
        run: |
          cd ios
          pod repo update
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
      - name: Build iOS app
        run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x" # Version stable de Java
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle --release
      - name: Decrypt keystore
        run: echo ${{ secrets.KEYSTORE_PASSWORD }} | base64 --decode > android/app/keystore.jks
      
