name: Flutter CI/CD

on:
  push:
    branches:
      - main  # Ou la branche que tu souhaites surveiller

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      # 3. Installer les dépendances
      - name: Install dependencies
        run: flutter pub get

      # 4. Construire l'AppBundle pour Android
      - name: Build Android AppBundle
        run: flutter build appbundle --release

      # 5. Décrypter le keystore
      - name: Set up keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          # Create the keystore file from base64
          if [ -n "$KEYSTORE_BASE64" ]; then
            echo "Creating keystore file from secret..."
            echo $KEYSTORE_BASE64 | base64 --decode > android/app/upload-keystore.jks
            
            # Create key.properties file
            echo "Creating key.properties file..."
            echo "storePassword=$STORE_PASSWORD" > android/key.properties
            echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
            echo "keyAlias=$KEY_ALIAS" >> android/key.properties
            echo "storeFile=../app/upload-keystore.jks" >> android/key.properties
            
            echo "Keystore and key.properties created successfully"
          else
            echo "No keystore secret found, using debug signing"
          fi

      # 6. Signer l'AppBundle
      - name: Sign AppBundle
        run: |
          cd android
          ./gradlew bundleRelease

      # 7. Télécharger l'outil "Google Play Publisher"
      - name: Download Google Play Publisher
        run: npm install -g fastlane

      # 8. Déployer sur Google Play
      - name: Deploy to Google Play
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          fastlane supply --aab build/app/outputs/bundle/release/app-release.aab \
          --track production \
          --json_key_data "$SERVICE_ACCOUNT_JSON" \
          --package_name fr.beehiveapp.beehive
