name: 🚀 Beehive CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x" # Version stable de Java
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      # - run: flutter analyze
      # - run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x" # Version stable de Java
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - name: Set platform version in Podfile
        run: |
          cd ios
          echo "platform :ios, '15.5'" >> Podfile
      - name: Update CocoaPods repo
        run: |
          cd ios
          pod repo update
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      # 3. Installer les dépendances
      - name: Install dependencies
        run: flutter pub get

      # 4. Construire l'AppBundle pour Android
      - name: Build Android AppBundle
        run: flutter build appbundle --release --verbose
