name: CI
on:
  push:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x" # Version stable de Java
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      # - run: flutter analyze
      # - run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x" # Version stable de Java
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - name: Set platform version in Podfile
        run: |
          cd ios
          echo "platform :ios, '15.5'" >> Podfile
      - name: Update CocoaPods repo
        run: |
          cd ios
          pod repo update
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
      - name: Build iOS app
        run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x" # Version stable de Java
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - name: Clean Flutter and Gradle Cache
        run: |
          flutter clean
          rm -rf ~/.gradle/caches/
          rm -rf android/.gradle/

      - name: Build App Bundle (Without Signing)
        run: flutter build appbundle --release --verbose --no-signing

      - name: Upload App Bundle Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab
      
